/**
 * GET /api/mobile/invoices/list
 *
 * List all invoices generated by the authenticated freelancer, newest-first.
 * Cursor-based pagination via ?cursor=<invoiceId>.
 *
 * Auth:  Bearer <mobile JWT>
 *
 * 200: {
 *   data: [{ id, orderId, invoiceNumber, pdfUrl, createdAt, amountUsdc, amountEurAtTx, buyerHandle, buyerLegalName, orderTitle }],
 *   meta: { nextCursor }
 * }
 */
import { NextRequest } from "next/server";
import db from "@/lib/db";
import { withMobileAuth, MobileTokenPayload } from "../../_lib/auth";
import { ok, err } from "../../_lib/response";

const DEFAULT_LIMIT = 20;
const MAX_LIMIT     = 50;

async function handler(req: NextRequest, user: MobileTokenPayload) {
  const sp     = req.nextUrl.searchParams;
  const cursor = sp.get("cursor");
  const limit  = Math.min(MAX_LIMIT, parseInt(sp.get("limit") ?? String(DEFAULT_LIMIT), 10));

  let cursorDate: Date | undefined;
  if (cursor) {
    const pivot = await db.invoice.findUnique({
      where: { id: cursor },
      select: { createdAt: true },
    });
    if (pivot) cursorDate = pivot.createdAt;
  }

  const invoices = await db.invoice.findMany({
    where: {
      userId:    user.sub,
      ...(cursorDate ? { createdAt: { lt: cursorDate } } : {}),
    },
    orderBy: { createdAt: "desc" },
    take: limit,
    select: {
      id:            true,
      orderId:       true,
      invoiceNumber: true,
      pdfUrl:        true,
      createdAt:     true,
      amountUsdc:    true,
      amountEurAtTx: true,
      buyerHandle:   true,
      buyerLegalName: true,
      order: {
        select: {
          gig:   { select: { title: true } },
          offer: { select: { title: true } },
        },
      },
    },
  });

  if (!invoices) return err("Something went wrong.", 500);

  const data = invoices.map((inv) => ({
    id:            inv.id,
    orderId:       inv.orderId,
    invoiceNumber: inv.invoiceNumber,
    pdfUrl:        inv.pdfUrl,
    createdAt:     inv.createdAt.toISOString(),
    amountUsdc:    inv.amountUsdc,
    amountEurAtTx: inv.amountEurAtTx ?? null,
    buyerHandle:   inv.buyerHandle ? `@${inv.buyerHandle}` : null,
    buyerLegalName: inv.buyerLegalName ?? null,
    orderTitle:    inv.order.offer?.title ?? inv.order.gig.title,
  }));

  const nextCursor = data.length === limit ? invoices[invoices.length - 1].id : null;

  return ok(data, { nextCursor });
}

export const GET = withMobileAuth(handler);
